apiVersion: dp.wso2.com/v1alpha2
kind: API
metadata:
  name: springboot-helloworld-api
  labels:
    api-name: "springboot-helloworld-api"
    api-version: "1.0.0"
    organization: "default"
    managed-by: "apk"
spec:
  apiName: SpringBoot Helloworld API
  apiType: REST
  apiVersion: 1.0.0
  basePath: /spring/1.0.0
  organization: "default"
  isDefaultVersion: false
  production:
  - routeRefs:
    - prod-http-route-springboot-helloworld
  sandbox: null
  apiProperties: []
status: null
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: prod-http-route-springboot-helloworld
  labels:
    api-name: "springboot-helloworld-api"
    api-version: "1.0.0"
    organization: "default"
    managed-by: "apk"
spec:
  hostnames:
    - default.gw.wso2.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: wso2-apk-default
      sectionName: httpslistener
  rules:
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: springboot-helloworld-backend
    matches:
    - method: GET
      path:
        type: RegularExpression
        value: /hello
---
apiVersion: dp.wso2.com/v1alpha1
kind: Backend
metadata:
  name: springboot-helloworld-backend
  labels:
    api-name: "springboot-helloworld-api"
    api-version: "1.0.0"
    organization: "default"
    managed-by: "apk"
spec:
  basePath: /
  protocol: http
  services:
  - host: spring-helloworld-service.default.svc
    port: 8080