apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-helloworld-deployment
spec:
  selector:
    matchLabels:
      app: spring-helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-helloworld
    spec:
      containers:
      - name: spring-helloworld
        image: devxdineshw/spring-helloworld:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-helloworld-service
spec:
  selector:
    app: spring-helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
